
export const GET_ALBUMS_REQUEST = 'GET_ALBUMS_REQUEST';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_ERROR = 'GET_ALBUMS_ERROR';

export const UPDATE_ALBUMS_REQUEST = 'UPDATE_ALBUMS_REQUEST';
export const UPDATE_ALBUMS_SUCCESS = 'UPDATE_ALBUMS_SUCCESS';
export const UPDATE_ALBUMS_ERROR = 'UPDATE_ALBUMSS_ERROR';
